name: fo
description: Implementation of assoc, assocIn and getIn for dart
version: 0.0.1
author: Maksim Ryzhikov <email@example.com>
homepage: https://github.com/maksimr/fo

environment:
  sdk: '>=1.20.0 <3.0.0'

dev_dependencies:
  test: '>=0.12.24+2 <0.13.0'
